Sybit-Education/Diveni

frontend/src/components/CopySessionIdPopup.vue

- Add fallback for copying text into clipboard. Used when a secure origin is not given.

Add fallback for copy into clipboard

---

frontend/src/components/CopySessionIdPopup.vue

optimize format of sessionId

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/CopySessionIdPopup.vue
frontend/src/locales/de.json
frontend/src/locales/en.json

- Add button in the popover to toggle qr code view
- Add qr code which leads to the current session

Add qr-code to invite others

---

.github/workflows/vuepress-deploy.yml

Fix vuepress deploy on PRs

---

.github/workflows/backend.yaml

fix: test workflow fails for pull-requests from forks

---

.github/workflows/diveni-deploy.yml

* Switch from ssh password to key authentication

#279 SSH: switch from password to key authentication

---

docs/.vitepress/config.js

* Change the URL redirection of the GitHub icon

fix: change url for the GitHub icon

---

frontend/src/components/MarkdownEditor.vue

Removed the invoke function call. Looks like everything works as usual even without it.

#284 Console error when creating a new session with user stories 

---

frontend/src/views/SessionPage.vue

Just added a clearStore commit, when the session page gets created and it seems to work.

#291 Starting new session while another is active

---

frontend/src/views/SessionPage.vue

Reverts Sybit-Education/Diveni#293
This PR breaks the ability to import user stories.

Revert "#291 Starting new session while another is active"

---

frontend/src/store/index.ts
frontend/src/views/SessionPage.vue

fixed the bug where imported user stories also get deleted

Starting new session while another is active + imported User Stories wont get deleted

---

frontend/src/views/LandingPage.vue

Typo in the landing page

---

frontend/src/components/EstimateTimer.vue
frontend/src/views/MemberVotePage.vue
frontend/src/views/SessionPage.vue

add a voting started bool to check if timer should count down

Timer does not reset, when creating a new session #359

---

docs/.vitepress/config.js
docs/guide.md
docs/guide/translations.md
package-lock.json
package.json

New guide how to maintain translations added to docs.

Feature: translations guide added

---

frontend/src/components/UserStoryDescriptions.vue

fixed font color not changing when changing theme

Fix the font color of the text area

---

frontend/src/components/FeedbackButton.vue

Feedback bugfix

---

backend/src/main/resources/logback-spring.xml

Replaced logging formats by formats provided by spring boot.

Simplify logging format to defaults

---

backend/build.gradle
backend/src/main/java/io/diveni/backend/config/CorsConfig.java
backend/src/main/java/io/diveni/backend/service/projectmanagementproviders/azuredevops/AzureDevOpsService.java
backend/src/main/java/io/diveni/backend/service/projectmanagementproviders/jiracloud/JiraCloudService.java
backend/src/main/java/io/diveni/backend/service/projectmanagementproviders/jiraserver/JiraServerService.java
backend/src/main/resources/logback-spring.xml
backend/src/test/java/io/diveni/backend/controller/WebsocketControllerTest.java
backend/src/test/resources/application-test.properties

Should be tested! Mayor update of spring-boot from 2.x -> 3.1.5

Upgrade spring boot to 3.1.5

---

frontend/src/components/SignInWithJiraButtonComponent.vue
frontend/src/components/SignInWithJiraServerButtonComponent.vue
frontend/src/views/SessionPage.vue

Fix for #509 
Aligning via row instead of col

Fix: Misalignment of the finish session button for the admin

---

backend/src/main/java/io/diveni/backend/model/Statistic.java
backend/src/main/java/io/diveni/backend/service/DatabaseService.java
frontend/src/views/SessionPage.vue

As my previous pull request:  484 diveni stat - draft #489 served as a quick draft to address the architecture of logging statistics, I've made several enhancements. These include transitioning to immutable fields for improved predictability, avoidance of side effects and easier debugging. Additionally, I've consolidated the increment methods for better organization.
The functionality should not be affected by these changes.

 Improvements for 484 diveni stat - draft #489 

---

frontend/src/components/UiToastEditorWrapper.vue

Fix: Markdown Editor updates on every input #560 

---

frontend/src/components/KickUserWrapper.vue

Fix: Admins can no longer kick members #562 

---

backend/src/main/java/io/diveni/backend/config/RestTemplateConfig.java
backend/src/main/java/io/diveni/backend/controller/ErrorMessages.java
backend/src/main/java/io/diveni/backend/controller/NewsController.java
backend/src/main/java/io/diveni/backend/model/Session.java
backend/src/main/java/io/diveni/backend/model/news/PullRequest.java
backend/src/main/java/io/diveni/backend/service/WebSocketService.java
backend/src/main/java/io/diveni/backend/service/news/GithubApiService.java
backend/src/test/java/io/diveni/backend/controller/NewsControllerTest.java
backend/src/test/java/io/diveni/backend/model/news/PullRequestTest.java

Introduced several null checks for the AdminVote object, and if it's missing, a new empty one will be created to ensure the AdminVote is displayed in that scenario as well.

fix: HostVoting Bug #555 

---

frontend/src/components/NotifyMemberComponent.vue

Fix: Members no longer receive information about whether the admin is in the session or not #563 

---

frontend/package-lock.json
frontend/package.json

Reverts Sybit-Education/Diveni#623

Revert "chore(deps): bump @vue/compat from 3.4.6 to 3.4.15 in /frontend"

---

frontend/src/views/SessionPage.vue

fixed the avatar image overflow when starting the session and also improved the mobile view.

fix: image overflow

---

frontend/src/components/ProjectSelectionComponent.vue

Fix: Improve project selection style #675 

---

frontend/.eslintrc.js
frontend/src/components/DownloadPWAModal.vue
frontend/src/components/JiraComponent.vue
frontend/src/components/MemberVoteCard.vue
frontend/src/components/SignInWithGitlabButtonComponent.vue
frontend/src/components/actions/SessionLeaveButton.vue
frontend/src/services/api.service.ts
frontend/src/views/LandingPage.vue
frontend/src/views/MemberVotePage.vue
frontend/src/views/SessionPage.vue
frontend/vue.config.js

Removed prettierprettier console spam and fixed some lints

Fix: 703 remove prettierprettier console spam

---

frontend/src/views/SessionPage.vue

Fix: Userstory selected during pre-planning is not transmitted

---

frontend/src/views/MemberVotePage.vue
frontend/src/views/SessionPage.vue

Fix: Incorrect sending of the initial selected User Story (Issue-Tracker Mode) #776 

---

frontend/src/views/SessionPage.vue

Fix: MessageConversionException: Cannot convert from [[B] to [java.lang.Integer] in Spring Messaging #788 

---

frontend/src/components/UserStoryTitle.vue

Fix: Missing border colors (estimate button and user story search field) #829 

---

.github/workflows/backend.yaml
.github/workflows/frontend.yaml

Fix: Deprecated version of actions/upload-artifact: v2

---

frontend/src/views/PrepareSessionPage.vue

Fix:  Wrong color of mode selection icon title #860 

---

backend/src/main/java/io/diveni/backend/service/projectmanagementproviders/jiraserver/JiraServerService.java

Fix: No Description When Creating an Issue (Jira Server)

---

.github/workflows/badges.yaml

Update badges - v2.yaml

---

.github/workflows/docs-deploy.yaml
docs/guide/develop.md

Test PR. Testing new docs-deployment actions

TEST: deprecated 'docs-deploy.yaml' workflow
